### ISSUE TITLE
하이라이트 기획 및 디자인 변경

### ISSUE THREAD

**Issue by onlyeye26** [realmani0/DigitalTextbook2018#1]
기존의 하이라이트 추가 및 편집을 하나의 팝업창을 공통으로 사용하도록 변경

디자인은 컨펌이 된 상태이고, 이미지 슬라이스 되면 전달해 드리면서
내용을 설명해 드리겠습니다.

**Comment by realmani0** [comment]
** 하이라이트 등록
 - 선택메뉴에서 하이라이트 선택시 팝업창이 뜸
 - 팝업이 뜨면 선택메뉴는 닫힘
 - 색을 선택하면 창이 자동으로 닫힘
 - 최초 하이라이트 설정시 하이라이트 슬라이드 보기와 삭제 버튼은 비활성화


** 하이라이트 수정
 - 하이라이트 클릭시 팝업창이 뜸
 - 팝업에서 색 변경, 닫기, 삭제, 하이라이트 슬라이드 가능
 - 색 변경시 팝업이 자동으로 닫힘
 - 하이라이트 슬라이드 실행시 하이라이트 팝업은 닫힘

**Comment by realmani0** [comment]
참고) 하이라이트 수정시 선택 된 색을 보여주기 위해서는 호환성 테스트가 필요.
- json 의 파라메터가 색이 추가 저장되어야 함. 
- 콘텐츠에서 하이라이트 클릭시 콘텐츠에서 뷰어의 HIGHLIGHT_POPUP을 호출.

**Comment by realmani0** [comment]
3/26 받음

전체 740 x 754 : width: 370px / height: 377px

파란색 높이 : 270px -> 135px
버튼 : width: 84px / height: 84px

**Comment by realmani0** [comment]
테스트 버전 배포

**Comment by onlyeye26** [comment]
내부 테스트 결과(3/28)
- 편집창일때 선택한 하이라이트의 색 표시 필요
- 안드로이드 테블릿(A6)에서 슬라이드와 삭제 사이에 하얀 실선이 보임(갤럭시S4에서는 현상 없음)
![IMG_4368](https://user-images.githubusercontent.com/20455074/55139515-4f02ff80-5179-11e9-9540-05c6a5ab9989.jpg)
- 안드로이드/iOS 핸드폰 가로 및 세로모드에서 팝업 창이 잘림
![IMG_4369](https://user-images.githubusercontent.com/20455074/55139559-64782980-5179-11e9-87a2-5d50a7a8428f.PNG)
![IMG_4370](https://user-images.githubusercontent.com/20455074/55139566-67731a00-5179-11e9-9ade-5ccf53dfd3f1.PNG)

**Comment by realmani0** [comment]
1/4 배포완료
